version: "3.5"

services:
  drdwns:
    image: docker-remote-desktop-debian-wine-nosound:latest
    hostname: docker-desktop
    restart: unless-stopped
    environment:
        - TZ=UTC
    ports:
        - "3389:3389/tcp"
    volumes:
        - data:/data
        
volumes:
    data: 
